[[Agama]]
arch = "aarch64"
git-tree-sha1 = "ca6d2036507c55c2f70c3dd6003930a868ddf778"
os = "macos"

    [[Agama.download]]
    sha256 = "2a845cf5f407e5384e1af01b562e71082d67cdfe317cd65c1e3bcd82126d47d8"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.aarch64-apple-darwin.tar.gz"
[[Agama]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6146d6baf8fdd6540167ff0ba9cd67ab2d5afb68"
libc = "glibc"
os = "linux"

    [[Agama.download]]
    sha256 = "a460c9d8a2f093fa76df680fefa76c76128a042df0a9d8d8481d242f31fca3eb"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Agama]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00d53205e2c06057011b32be62bd9e31ff445338"
libc = "glibc"
os = "linux"

    [[Agama.download]]
    sha256 = "0819aea1873070271aaaac910a1dfcab870fb230d849bebcd0b9804887131e18"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Agama]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d259ac432e3c71cc0def1157c02d7fac588019e5"
libc = "glibc"
os = "linux"

    [[Agama.download]]
    sha256 = "c2d0a0cc0df47f1a5c9da3c63d3eaf55a2b84d7ec139a6e7f9f27df933371107"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Agama]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74d1990c99641591bb1a5fab1e2a620aba6e96ab"
libc = "glibc"
os = "linux"

    [[Agama.download]]
    sha256 = "1799cc857087aee5b2787a5a28163d5badc7521e97a995c9a4c147771e93d9ad"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.i686-linux-gnu-cxx11.tar.gz"
[[Agama]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a884c0a54f90861ccb22ad6f4bf627ca0ea73538"
libc = "glibc"
os = "linux"

    [[Agama.download]]
    sha256 = "91ac11fa9e7477a7a791e42d2f730d964b91a6686e3184bccee5ac180f488175"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Agama]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6746fb6d34ad6407b53545558653828c5d5468f"
libc = "glibc"
os = "linux"

    [[Agama.download]]
    sha256 = "04cafc5108cf413ed205d8f9c709baeaacf6c7e86eb89e092c3f48c5b870b39d"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.riscv64-linux-gnu-cxx11.tar.gz"
[[Agama]]
arch = "x86_64"
git-tree-sha1 = "081945181f5841795355cbd736939d51374e5df0"
os = "macos"

    [[Agama.download]]
    sha256 = "a95265cbfdf8290895de33ba4bd7dfd6d878752197471b8e3747624aabf7c34a"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.x86_64-apple-darwin.tar.gz"
[[Agama]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fe5aa61aa0a68475566b2b8eeac709a12f35648"
libc = "glibc"
os = "linux"

    [[Agama.download]]
    sha256 = "941e0d8bd708931e360898b8f5090e79942a2c41ce3ac5806776caa7a5242571"
    url = "https://github.com/JuliaBinaryWrappers/Agama_jll.jl/releases/download/Agama-v1.1.0+0/Agama.v1.1.0.x86_64-linux-gnu-cxx11.tar.gz"
