# Autogenerated wrapper script for Agama_jll for aarch64-apple-darwin
export libagama

using GSL_jll
using LLVMOpenMP_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Agama")
JLLWrappers.@declare_library_product(libagama, "@rpath/libagama.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GSL_jll, LLVMOpenMP_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libagama,
        "lib/libagama.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
